-- food_inspections definition

CREATE TABLE food_inspections (
	inspection_id INTEGER NOT NULL,
	dba_name TEXT,
	aka_name TEXT,
	license_number INTEGER,
	facility_type TEXT,
	risk TEXT,
	address TEXT,
	city TEXT,
	state STRING,
	zip INTEGER,
	inspection_date DATE,
	inspection_type TEXT,
	results TEXT,
	violations TEXT,
	latitude NUMERIC,
	longitude NUMERIC,
	location TEXT,
	dba_name_clean TEXT,
	dba_name_cleancluster TEXT,
	aka_name_clean TEXT,
	aka_name_cleancluster TEXT,
	facility_type_clean TEXT,
	facility_type_cleancluster TEXT,
	address_clean TEXT,
	city_clean TEXT,
	inspection_date_clean DATE,
	inspection_type_clean TEXT,
	inspection_type_cleancluster TEXT,
	location_clean TEXT,
	violations_numbers TEXT,
	city_cleancluster TEXT,
	CONSTRAINT FOOD_INSPECTIONS_PK PRIMARY KEY (inspection_id)
);
